from pathlib import Path
import re,html,json
ROOT=Path(__file__).resolve().parents[1]
NAMES=['sbs-contexto-ejecucion','sbs-contratos-gobierno','sbs-fundacion-datos','sbs-versiones-cambios','sbs-rag-hibrido','sbs-modelos-configuracion','sbs-genie-datos','sbs-conversacion-orquestacion','sbs-guardrails-permisos','sbs-evaluacion-jueces','sbs-canal-revision','sbs-observabilidad-operacion','sbs-despliegue-e2e']
ROLES=['Recuperar contexto, fijar entradas y coordinar dependencias','Definir contratos, roles y estados de documentos y respuestas','Capturar PDF, preservar originales y extraer texto trazable','Alinear versiones y registrar diferencias antes/después','Construir recuperación léxica/vectorial, RRF, reranking y citas','Fijar modelos, tokenizer, identidad, endpoints y límites','Curar tablas, publicar y configurar consultas Genie','Resolver contexto, enrutar herramientas y componer conversación','Aplicar permisos, fuentes permitidas y validaciones de evidencia','Evaluar calidad mediante casos, referencias y jueces independientes','Construir y probar novedades, comparación, chat y fuentes','Instrumentar trazas y operar captura/publicación con control de fallos','Empaquetar notebooks/App y comprobar entrega y recuperación E2E']
EVIDENCE=['Contexto y artefactos reutilizados con identidad y hashes.','Contratos aplicados; conversación separada de aprobación institucional.','Seis copias reales ingeridas y extraídas; cobertura completa no acreditada.','Dos pares usados en comparaciones; alineación y calidad generales pendientes.','RAG integrado en las muestras; evaluación general y discrepancia histórica del reranker pendientes.','Embedding, reranker local y generación integrados en el piloto; no certifica cualquier selección futura.','Conteos y tablas del piloto probados; límites de alcance y procedencia documentados.','Comparación, seguimiento y propuestas probados por muestra; generalización pendiente.','Controles de identidad, alcance, citas y cupos en el alcance revisado; no auditoría universal.','Muestras revisadas por IA; holdout independiente completo y métricas por familia pendientes.','Recorridos reales de App probados; la guía local/Foquito es un artefacto diferente.','Writer real y readback documentados; Job diario pausado y recuperación cloud pendiente.','App y evidencia histórica de notebooks disponibles; aceptación completa del spec sigue abierta.']
MAP=[([0,1],[8,9]),([2],[0,1,8,11]),([2],[1,8,9]),([3],[1,2,9]),([4,5],[1,2,8,9]),([6,11],[1,3,4,8,12]),([7,8],[1,10,11]),([4,5],[3,7,8,9]),([6,7],[1,8,11]),([7,8],[3,5,9]),([10,12],[7,8,11]),([9,11,12],[0,5,8])]
def build(steps):
 records=[]
 for i,name in enumerate(NAMES):
  path=ROOT/'skills'/name/'SKILL.md';text=path.read_text();match=re.search(r'Versi[oó]n\s*([0-9]+\.[0-9]+\.[0-9]+)',text)
  records.append({'id':f'SK{i:02}','name':name,'version':match.group(1) if match else 'ver SKILL.md','status':'Provisional','role':ROLES[i],'component_evidence':EVIDENCE[i],'path':'../skills/'+name+'/SKILL.md','evals':'../skills/'+name+'/evals/cases.json'})
 def link(i):
  s=records[i];return '<a href="'+s['path']+'" target="_blank" rel="noopener">'+s['id']+' · '+html.escape(s['name'])+'</a>'
 rows=''.join('<tr><td><a href="#paso'+str(i)+'">Paso '+str(i)+'</a><br><strong>'+html.escape(steps[i-1][0])+'</strong></td><td>'+html.escape(steps[i-1][3])+'</td><td>'+', '.join(link(n) for n in main)+'</td><td>'+', '.join(link(n) for n in support)+'</td></tr>' for i,(main,support) in enumerate(MAP,1))
 catalogue=''.join('<details><summary>'+s['id']+' · '+html.escape(s['name'])+' · v'+s['version']+' · provisional</summary><p><strong>Responsabilidad:</strong> '+html.escape(s['role'])+'.</p><p><strong>Evidencia del componente:</strong> '+html.escape(s['component_evidence'])+'</p><p>'+link(i)+' · <a href="'+s['evals']+'" target="_blank" rel="noopener">Casos de evaluación</a></p></details>' for i,s in enumerate(records))
 section='<section id="skills"><span class="tag">TRAZABILIDAD DE CONSTRUCCIÓN · SK00–SK12</span><h2>Qué skill corresponde a cada paso</h2><p><strong>13 creadas; 13 provisionales; ninguna declarada de producción.</strong> Los archivos registran creación mediante skill-creator-z. El estado de una skill, la prueba de su componente y la aceptación E2E son tres estados distintos.</p><p>Esta matriz asigna responsabilidades de construcción, evaluación y mantenimiento; no afirma que cada pregunta invoque todas las skills. El runtime ejecuta código y adaptadores. Los recursos de instrucciones que utiliza permanecen versionados bajo la skill responsable.</p><p>Principal significa que produce el resultado del paso. Apoyo significa que aporta contratos, datos, controles o evaluación. SK09 revisa muestras y regresiones: no implica ejecutar un juez independiente en cada consulta. SK00 acompaña la coordinación de todo el trabajo.</p><table><thead><tr><th>Paso docente</th><th>¿En qué consiste?</th><th>Skills principales</th><th>Skills de apoyo / revisión</th></tr></thead><tbody>'+rows+'</tbody></table><h3>Catálogo y estado real</h3>'+catalogue+'<h3>Cómo explicarlo a los alumnos</h3><div class="say"><p>“Cada skill es un procedimiento reutilizable: cuándo usarlo, qué entradas necesita, qué entrega y cómo se comprueba. Por ejemplo, SK02 prepara la evidencia; SK04 y SK05 permiten encontrarla; SK07 coordina una respuesta; SK08 comprueba controles; SK09 evalúa su calidad; SK10 la presenta y SK12 verifica la entrega.”</p></div><p><strong>Nota de continuidad:</strong> los planes iniciales conservan la frase “ninguna creada” como estado histórico. Para el estado actual se usa cada SKILL.md y ESTADO-ENTREGA; no se han reescrito los planes ni promovido skills por añadir esta guía.</p></section>'
 data={'date':'2026-09-30','meaning':'responsibility mapping, not per-request invocation trace','skills':records,'steps':[{'step':i,'title':steps[i-1][0],'summary':steps[i-1][3],'primary':[records[n]['id'] for n in a],'support':[records[n]['id'] for n in b]} for i,(a,b) in enumerate(MAP,1)]}
 (Path(__file__).parent/'skills.json').write_text(json.dumps(data,ensure_ascii=False,indent=2))
 return section,MAP,link
