"""Narrativa S08. Las cifras de ejecución se agregan sólo desde evidencia validada."""
from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]
slides=[]
REF={
'serving':'https://docs.databricks.com/aws/en/machine-learning/model-serving/',
'endpoint':'https://docs.databricks.com/aws/en/machine-learning/model-serving/create-manage-serving-endpoints',
'alias':'https://docs.databricks.com/aws/en/machine-learning/manage-model-lifecycle/',
'bundles':'https://docs.databricks.com/aws/en/dev-tools/bundles/',
'env':'https://docs.databricks.com/aws/en/dev-tools/bundles/deployment-modes',
'auth':'https://docs.databricks.com/aws/en/dev-tools/databricks-apps/auth',
'app':'https://docs.databricks.com/aws/en/dev-tools/databricks-apps/model-serving',
'inference':'https://docs.databricks.com/aws/en/ai-gateway/inference-tables-serving-endpoints',
'monitor':'https://docs.databricks.com/aws/en/data-governance/unity-catalog/data-quality-monitoring/data-profiling/create-monitor-api',
'gateway':'https://docs.databricks.com/aws/en/ai-gateway/overview-serving-endpoints',
'prompt':'https://docs.databricks.com/aws/en/mlflow3/genai/prompt-version-mgmt/prompt-registry/',
'exam':'https://www.databricks.com/sites/default/files/2026-03/Databricks-Certified-Generative-AI-Engineer-Associate-Exam-Guide-Mar26.pdf',
'gcp':'https://docs.cloud.google.com/vertex-ai/docs/predictions/overview',
'azure':'https://learn.microsoft.com/en-us/azure/machine-learning/concept-endpoints?view=azureml-api-2',
'aws':'https://docs.aws.amazon.com/sagemaker/latest/dg/realtime-endpoints.html'}
def add(title,body,notes,req,kind='pair',refs='',ey='S08 · Del notebook al servicio'):
 slides.append(dict(id=f'slide-{len(slides)+1:02}',title=title,body=body,notes=notes,requirements=req.split(),kind=kind,refs=[REF[x] for x in refs.split()],ey=ey))
add('El copiloto termina cuando otro usuario puede operarlo', ['Neptuno: del agente evaluado a un servicio con interfaz y monitoreo.','Última clase · lunes 28 de septiembre de 2026 · 180 minutos'], 'Retomar S05 agente, S06 evaluación y S07 controles. Preguntar qué se rompe si cerramos nuestro notebook: sesión, credenciales, variables y cómputo. Hoy empaquetamos esas dependencias y conservamos la evidencia. El objetivo es un despliegue de laboratorio reproducible; la autorización productiva requiere criterios del negocio.', 'S08-FINAL S08-CONTINUITY','hero')
add('La clase conecta una llamada con su evidencia', [('0–85','Empaquetar, servir y versionar'),('85–95','Pausa'),('95–145','App y monitoreo'),('145–180','CI/CD, prompts y cierre')], 'Agenda estimada. El instructor prepara los recursos cloud antes de entrar: creación del endpoint, App y primera actualización del monitor pueden superar un bloque. La práctica utiliza recursos individuales o recursos docentes accesibles; los resultados previos se identifican por ejecución. Consultar agenda.json para el desglose definitivo.', 'S08-FINAL','flow')
add('Cada entrega debe permitir repetir una decisión', [('Construcción','Código, dependencias, configuración y versión fija.'),('Operación','Solicitud, respuesta, identidad, métricas y rollback.')], 'Mostrar CONSIGNA.md antes de la demo. Un enlace que abre es necesario pero no suficiente: el evaluador debe reconstruir con qué versión respondió el agente, qué controles aplicaron y qué se haría si la calidad cae. Separar archivos proporcionados de salidas que generará el alumno.', 'S08-FINAL')
add('Neptuno conserva datos, herramientas y controles', [('S01–S04','Gold y documentos con procedencia.'),('S05','Agente que decide qué herramienta invocar.'),('S06–S07','Casos de evaluación y fronteras de seguridad.'),('S08','Servicio, interfaz y señales operativas.')], 'No cambiar de proyecto al llegar a producción. Si alguna tabla o función falta, recuperar su sesión. No sustituir una tool por una respuesta escrita a mano. El empaquetado cambia el acceso técnico a los datos: el resultado de negocio debe pasar nuevamente las pruebas de regresión.', 'S08-CONTINUITY','flow')
add('Una solicitud cruza tres identidades diferentes', [('Persona','Se autentica para usar la App.'),('App','Su backend solicita una inferencia.'),('Servicio','Lee sólo los recursos autorizados.')], 'Dibujar las fronteras: navegador → backend de App → endpoint → datos/herramientas. Una App con identidad propia no hereda automáticamente todos los permisos de cada usuario. Debemos elegir app authorization o user authorization conscientemente y comprobar los permisos en cada salto. No poner un PAT en JavaScript.', 'S08-APPS S08-CONTINUITY','flow','auth')
add('Antes de desplegar comprobamos el acceso necesario', ['Abre el notebook S08 y ejecuta CP0 con tu catálogo y recursos.','Aceptación: inventario explícito; una ausencia detiene el paso que depende de ella.'], 'Explicar workspace, catálogo, esquema y warehouse al aparecer. Verificar capacidad de registrar modelos, crear endpoint/App y tablas. Completar las variables de alumno desde la guía; las coordenadas docentes son evidencia, no credenciales compartidas. Un warehouse detenido puede arrancar al ejecutar SQL.', 'S08-FINAL','task')
add('Model Serving reúne tres tipos de servicio', [('Custom models','Tu artefacto y su código de inferencia.'),('Foundation Model APIs','Modelos administrados disponibles mediante API.'),('External models','Acceso gobernado a un proveedor externo.')], 'Nuestro agente se empaqueta como artefacto custom y llama a un modelo base. Distinguir el endpoint del agente y el endpoint del LLM: tienen contratos, permisos y costos diferentes. La categoría seleccionada determina qué opciones de escalado y Gateway están disponibles.', 'S08-SERVING','flow','serving')
add('Serverless elimina servidores que administrar, no la espera', [('Autoscaling','Ajusta capacidad dentro de las condiciones del servicio.'),('Scale-to-zero','Reduce capacidad ociosa en configuraciones compatibles; añade arranque en frío.')], 'No prometer que todo endpoint soporta scale-to-zero ni latencia de milisegundos para un agente con LLM y SQL. Comparar una consulta interactiva y un proceso batch nocturno. Medir primera solicitud separada de solicitudes calientes. La configuración docente y el ensayo deben revelar el tradeoff.', 'S08-SERVING',refs='endpoint')
add('La latencia total suma más que el tiempo del modelo', [('Usuario','Red + App + cola + agente + herramientas + respuesta.'),('Servicio','Su métrica de ejecución puede cubrir sólo parte del recorrido.')], 'Ejemplo didáctico: una respuesta puede demorarse porque el warehouse arranca, aunque el LLM responda rápido. Mostrar timestamps de cliente y servicio cuando estén disponibles. No restar latencias tomadas con relojes no sincronizados ni comparar p95 de unas pocas llamadas como SLA.', 'S08-SERVING S08-MONITOR')
add('Un notebook depende de un contexto que Serving no tiene', [('En clase','spark, dbutils, %run y variables interactivas.'),('En el endpoint','Código importable, dependencias y acceso autenticado por API.')], 'Abrir el módulo del agente del laboratorio. Señalar qué acceso Spark fue reemplazado por SQL Statement Execution y dónde se valida la entrada. El código servido no debe necesitar que el docente haya ejecutado una celda previamente. Las dependencias quedan declaradas; para producción, congelar además el entorno resuelto y repetir las pruebas.', 'S08-DEPLOY S08-CONTINUITY')
add('Empaquetar el agente conserva su contrato de entrada y salida', [('Entrada','Mensajes y parámetros permitidos.'),('Salida','Texto y metadatos de trazabilidad; errores definidos.')], 'ResponsesAgent es una interfaz; no añade automáticamente razonamiento ni permisos. Validar una pregunta legítima, una ambigua y una maliciosa con el mismo contrato. El cuerpo de la petición debe coincidir con la firma registrada: messages de Chat Completions e input de Responses no son intercambiables.', 'S08-DEPLOY')
add('Registrar una versión fija permite repetir la prueba', ['Ejecuta CP1 y guarda nombre del modelo, versión y resultado local.','Aceptación: inferencia válida y controles del agente verificados antes de Serving.'], 'Mostrar el artefacto registrado y los recursos declarados. La versión es inmutable; el alias se puede mover. Si falla el test local del modelo empaquetado, no continuar creando endpoints en bucle. Revisar imports, paquetes, firma y permisos. Registrar el error y la corrección.', 'S08-DEPLOY S08-CONTINUITY','task','alias')
add('Deploy model y deploy code responden preguntas distintas', [('Deploy model','¿Qué artefacto probado promuevo al siguiente entorno?'),('Deploy code','¿Qué proceso versionado reconstruye y valida la solución allí?')], 'Ambos patrones tienen usos válidos. Promover el mismo artefacto conserva lo evaluado; ejecutar código en cada entorno también valida sus dependencias y datos, pero puede producir artefactos diferentes. Decidir qué congelar: código, prompt, modelo, paquetes y referencias. Evitar presentar un patrón como siempre superior.', 'S08-DEPLOY')
add('Un endpoint listo todavía necesita una prueba funcional', ['Ejecuta CP2 y envía una pregunta real al endpoint del agente.','Aceptación: READY, respuesta coherente, versión identificada y error controlado.'], 'READY significa disponible para recibir solicitudes; no prueba calidad. Comparar con la salida CP1 y registrar request_id cuando el servicio lo exponga. Un 401/403 dirige a autenticación/permisos; un error de modelo dirige a sus logs. No mostrar valores secretos en capturas.', 'S08-SERVING S08-FINAL','task','endpoint')
add('Los fallos enseñan qué frontera revisar primero', [('401 / 403','Identidad o autorización: verificar quién llama a qué recurso.'),('Timeout / 5xx','Estado, arranque, dependencia y logs: conservar la solicitud.')], 'Actividad de dos minutos: asignar un error al salto navegador/App/endpoint/warehouse. No reintentar ciegamente una operación con efectos. Para consultas de sólo lectura, usar reintentos limitados, backoff y timeout; devolver al usuario un mensaje útil sin stacktrace sensible.', 'S08-SERVING S08-APPS')
add('Un alias nombra una versión, no reparte tráfico', [('champion','Etiqueta mutable que apunta a una versión registrada.'),('Traffic split','Disponible en el endpoint custom del ejercicio, no en el agente.')], 'Primero distinguir capacidades: la documentación de Gateway marca traffic splitting para custom endpoints, no para endpoints de agentes administrados. El laboratorio principal es agent/v1/responses y no admite split. CP3 usa un endpoint custom complementario que consulta ventas reales de UC; no es otro agente. Demostrar que mover un alias no necesariamente actualiza un endpoint ya fijado a una versión. Leer la versión del alias y la configuración del endpoint por separado. Nuestro procedimiento resuelve el alias y configura explícitamente la versión deseada antes de probarla.', 'S08-ROLLOUT',refs='alias endpoint')
add('Canary limita exposición y A/B compara alternativas', [('Canary','Aumentar tráfico gradualmente si cumple los criterios.'),('A/B','Comparar variantes con asignación y métricas de experimento.')], 'Un split 90/10 es configuración probabilística, no garantía de nueve y una respuestas en diez llamadas. A/B requiere diseño de experimento: unidad de asignación, ventana, muestra y criterio. En CP3 las dos versiones custom implementan la misma consulta real: sólo se demuestra mecánica de enrutamiento y rollback, no superioridad de calidad.', 'S08-ROLLOUT',refs='endpoint')
add('Decidimos el rollback antes de observar el resultado', [('Criterio de calidad','Conservar casos S06 y rechazos S07.'),('Criterio operativo','Límite de errores y latencia con ventana y muestra definidas.')], 'Ejemplo de política didáctica: cualquier fuga confirmada detiene la promoción; errores y latencia se comparan contra un baseline del mismo entorno. No inventar umbrales universales. El alumno debe escribir criterio, responsable y versión anterior antes de lanzar el canary.', 'S08-ROLLOUT S08-CONTINUITY')
add('La práctica termina al restaurar y volver a consultar', ['CP3: en el endpoint custom de ventas, reparte 90/10 y ejecuta rollback.','Aceptación: configuración antes/después y una respuesta de la versión restaurada.'], 'No basta guardar el JSON del PUT; volver a consultar el endpoint. Diferenciar rollback del tráfico, rollback del prompt y rollback de datos. Preservar snapshots previos; trabajar exclusivamente sobre el endpoint del laboratorio. No alterar un servicio compartido del curso.', 'S08-ROLLOUT','task')
add('La pausa deja una versión estable para continuar', ['Guarda las coordenadas de tu endpoint y modelo.','Pausa de 10 minutos · al volver seguimos una solicitud hasta su tabla.'], 'Pausa real; no llenar estos diez minutos con explicación. Antes de pausar, confirmar que ningún alumno cambia recursos ajenos y que el instructor tiene una ejecución conocida. Un recurso todavía iniciándose se registra pendiente, no aprobado.', 'S08-FINAL','hero')
add('Una App convierte la API en una tarea para una persona', [('Interfaz','Pregunta, estado de espera, respuesta y error comprensible.'),('Backend','Valida entrada, llama al endpoint y conserva trazabilidad.')], 'Abrir app/ y explicar qué archivo inicia el servidor y cómo recibe configuración. La UI no debe exponer secretos, logs internos ni resultados crudos de herramientas. El navegador conversa con el backend autenticado, no con un PAT incrustado hacia el endpoint.', 'S08-APPS',refs='app')
add('Autenticar al usuario no garantiza filtrar sus datos', [('App authorization','La App usa su principal de servicio y los permisos asignados.'),('User authorization','Operaciones delegadas usan identidad/permisos del usuario donde estén soportados.')], 'En el laboratorio describir con exactitud el modo implementado. Si todos ven el mismo corpus autorizado con identidad de App, no afirmar seguridad por fila para cada usuario. La identidad del usuario no se transmite automáticamente por todos los saltos. Una ACL al endpoint controla invocación, no por sí sola autorización a cada dato.', 'S08-APPS S08-CONTINUITY',refs='auth')
add('Los recursos declarados evitan credenciales pegadas al código', [('Configuración','Endpoint del agente y permisos mínimos como recursos de la App.'),('Secreto','Autenticación gestionada sólo en el backend.')], 'Mostrar app.yaml y recursos de la aplicación. Distinguir un nombre de endpoint de una credencial. No poner valores de tokens en widgets, repositorio ni HTML. Si el SDK no autentica, corregir configuración del servicio; no resolver la falla pegando el token del docente.', 'S08-APPS',refs='app auth')
add('Probamos la interfaz con éxito y con error', ['CP4: abre la App con tu identidad y ejecuta una consulta legítima.','Aceptación: respuesta del endpoint y rechazo/aviso claro ante entrada inválida.'], 'Comparar la respuesta de la App con la llamada de CP2. Probar entrada vacía y una petición fuera de política. Verificar que el mensaje visible no muestra stacktrace ni credenciales y que el botón permite volver a intentar. Guardar evidencia del servicio y de la UI por separado.', 'S08-APPS S08-FINAL','task')
add('Una llamada correcta puede dejar evidencia incompleta', [('Inferencia','HTTP correcto y respuesta recibida.'),('Registro','Solicitud y respuesta disponibles después en una tabla.')], 'La escritura de tablas de inferencia es asíncrona y puede tardar. La ausencia momentánea de filas no implica que no haya tráfico. Anotar rango temporal y request_id, revisar configuración y esperar la ventana indicada antes de concluir una falla. No reemplazar una tabla vacía por filas inventadas.', 'S08-INFERENCE')
add('Inference Tables conservan el intercambio para analizarlo', [('Captura','Petición, respuesta y metadatos del servicio en Delta.'),('Uso','Investigar errores y construir métricas operativas.')], 'Usar AI Gateway-enabled inference tables vigentes. No modificar el schema de la tabla administrada. La tabla cruda contiene información potencialmente sensible: aplicar acceso y retención S07; para compartir resultados, exportar sólo métricas y casos sintéticos autorizados.', 'S08-INFERENCE',refs='inference')
add('Aplanar JSON convierte el intercambio en columnas medibles', [('Antes','Un request/response anidado, distinto según la API.'),('Después','ID, tiempo, estado, versión y métricas calculadas.')], 'Abrir la transformación real del laboratorio. Leer primero el schema observado: no copiar rutas JSON de una API distinta. Separar dato ausente de cero; conservar timestamp y versión. Deduplicar por identificador cuando la entrega de logs pueda repetir registros. No confundir longitud en caracteres con tokens facturados.', 'S08-INFERENCE')
add('Una fila defectuosa debe ser visible, no desaparecer', [('Caso válido','Payload parseado con sus campos esperados.'),('Caso no válido','Contador y razón de parseo; inspección restringida.')], 'Ejercicio: un cambio de formato mueve el texto de la respuesta. Si el flatten produce null, el dashboard no debe reportar respuesta de longitud cero como éxito. Preservar conteo de entradas, duplicados y errores de extracción. Un fixture de fallo es prueba de transformación, no tráfico real.', 'S08-INFERENCE')
add('Seguimos una solicitud real hasta su fila procesada', ['CP5: invoca el endpoint, localiza el registro y ejecuta el flatten.','Aceptación: correlación verificable y tabla procesada con métricas válidas.'], 'El instructor debe preparar registros con antelación; en clase se usa una ventana reciente y se distingue nueva llamada de evidencia previa. Comparar datos antes/después. Si la entrega del log tarda, registrar pendiente y revisar en el bloque de recuperación; no afirmar pipeline completo.', 'S08-INFERENCE S08-FINAL','task')
add('Monitorear operación y calidad exige señales distintas', [('Operación','Errores, latencia, volumen y consumo.'),('Calidad','Aciertos, evidencia, utilidad y controles del agente.')], 'S06 aporta los casos de referencia y la revisión humana. Un servicio rápido puede responder mal; una respuesta correcta puede tardar demasiado. Mantener denominadores explícitos para evaluar ambos. Alertas operativas disparan diagnóstico; no prueban por sí solas deterioro semántico.', 'S08-MONITOR S08-CONTINUITY')
add('Drift señala un cambio, no demuestra una falla', [('Cambio observado','Distribución reciente distinta de una referencia.'),('Investigación','Estacionalidad, nuevos usuarios, datos o versión del agente.')], 'Ejemplo Neptuno: llegan preguntas más largas después de habilitar el chat a otra área. La longitud cambia, pero todavía no sabemos si bajó la calidad. Revisar casos y ground truth. Distinguir drift de datos, caída de calidad y bug del parser.', 'S08-MONITOR')
add('El monitor necesita una tabla y una comparación', [('Perfil temporal','Métricas por ventana sobre la tabla procesada.'),('Baseline','Referencia documentada para interpretar cambios.')], 'Lakehouse Monitoring aparece hoy como data profiling dentro de data quality monitoring. El laboratorio configura un perfil compatible con sus columnas reales; una respuesta de texto no es automáticamente una etiqueta de clasificación. No forzar InferenceLog si los campos no cumplen su contrato.', 'S08-MONITOR',refs='monitor')
add('Crear el monitor no equivale a obtener métricas', ['CP6: solicita un refresh e inspecciona estado y tablas de salida.','Aceptación: actualización terminada, métricas localizables y límites interpretados.'], 'Separar configuración aceptada, refresh en curso y refresh terminado. Mostrar el dashboard cuando esté generado. Con pocas solicitudes la evidencia demuestra que el circuito funciona; no estima deriva poblacional ni garantiza ausencia de riesgo. Guardar IDs y timestamps del refresh.', 'S08-MONITOR S08-FINAL','task','monitor')
add('Una alerta útil indica quién debe hacer qué', [('Detección','Métrica, ventana, baseline y umbral acordados.'),('Respuesta','Responsable, diagnóstico, rollback y evidencia.')], 'En parejas redactar un runbook para aumento de errores: verificar despliegue reciente, revisar logs, limitar tráfico o restaurar versión y repetir smoke. Establecer qué señales necesitan revisión humana. No reentrenar ni cambiar prompt automáticamente por cualquier drift.', 'S08-MONITOR S08-ROLLOUT')
add('AI Gateway permite observar y limitar según el endpoint', [('Inference Tables','Contenido y metadatos para diagnóstico.'),('Usage / límites','Consumo y control del ritmo de solicitudes.')], 'La documentación actual también presenta Unity Gateway; su disponibilidad no es la misma para todos los tipos de endpoint. No confundir usage tables con un presupuesto en moneda. La compatibilidad de guardrails y rate limits depende del tipo de endpoint y de la versión del gateway. Inspeccionar las capacidades del endpoint S08. Una opción no soportada se documenta sin atribuirle protección.', 'S08-GATEWAY',refs='gateway')
add('El costo combina inferencia, servicio y datos', [('Por solicitud','Tokens o cargos del modelo, consultas y operaciones.'),('Por capacidad','Serving, App, warehouse y procesamiento de logs.')], 'Usar un cálculo hipotético identificado como tal: solicitudes × tokens medios × tarifa, más capacidad y almacenamiento. Las tarifas se consultan al diseñar; no congelar precios inventados. Scale-to-zero reduce parte del costo ocioso, no elimina todos los recursos del recorrido.', 'S08-GATEWAY')
add('El bundle describe recursos que podemos revisar en Git', [('Código','Agente, App, notebook y dependencias.'),('Configuración','Recursos, variables y targets del despliegue.')], 'Databricks Asset Bundles es el nombre del temario; la documentación actual usa Declarative Automation Bundles. Abrir bundle/databricks.yml del kit. Identificar variables, target y recursos de endpoint/App. Un bundle validate exitoso valida configuración, no ejecuta la aplicación ni prueba permisos de runtime.', 'S08-BUNDLES',refs='bundles')
add('Separar entornos exige más que cambiar un nombre', [('Laboratorio','Targets y prefijos aíslan recursos dentro del workspace disponible.'),('Producción','Identidades, catálogos y, cuando aplica, workspaces separados.')], 'No vender targets dev/prod en el mismo workspace como aislamiento total. Mostrar qué variable cambia entre targets y qué recursos comparten. Evitar que una configuración de desarrollo pueda escribir accidentalmente en los datos productivos. La topología exacta de clase queda en la guía.', 'S08-BUNDLES',refs='env')
add('La promoción se detiene si falla una puerta de calidad', [('1 · Validar','Sintaxis, tests y permisos previstos.'),('2 · Desplegar','Artefacto/configuración identificados.'),('3 · Comprobar','Smoke, evaluación y guardrails.'),('4 · Promover','Revisión, tráfico y rollback.')], 'CI ejecuta verificaciones por cambio; CD aplica una versión aprobada al entorno. El ejemplo de CI se entrega para adaptar a la cuenta del alumno: existencia del YAML no significa que una corrida remota de CI haya ocurrido. Separar bundle validado, recursos desplegados y pipeline CI ejecutado.', 'S08-BUNDLES','flow')
add('Podemos revisar el plan antes de desplegar el target', ['CP7: valida el bundle y examina el target del laboratorio.','Aceptación: validación del target y explicación de los recursos que aplicaría.'], 'El orden CP7 se explica aquí porque producción requiere repetibilidad; el notebook puede ejecutarlo al final. Dar comandos exactos desde bundle/. Cada alumno usa su propio perfil local y variables. No usar el nombre del perfil docente como prerequisito del starter.', 'S08-BUNDLES','task')
add('Versionar el prompt permite explicar qué cambió', [('Versión','Texto e instrucciones identificados y reproducibles.'),('Alias','Nombre para una versión aprobada después de evaluar.')], 'El prompt registry conserva versiones; cambiar un alias no garantiza que un proceso con caché recargue inmediatamente ni que el endpoint cambie su artefacto. Registrar versión efectivamente usada. Si el laboratorio congela el prompt en el modelo, una promoción requiere reconstrucción/despliegue explícito.', 'S08-PROMPTS',refs='prompt')
add('El rollback del prompt también necesita una prueba', ['CP7: registra dos versiones, compara y restaura el alias según la guía.','Aceptación: versión resuelta antes/después; el agente usa la versión declarada.'], 'CP7 registra una nueva versión didáctica, mueve y restaura el alias, y compara los IDs resueltos. El modelo servido fija el prompt en su artefacto: sigue usando la versión declarada aunque se mueva el alias. La prueba no despliega una regresión de conducta. Si se quisiera cambiar la conducta, habría que empaquetar, actualizar la versión única y repetir los casos S06/S07.', 'S08-PROMPTS S08-CONTINUITY','task','prompt')
add('El portafolio reúne el recorrido completo del copiloto', [('Datos y agente','Fuente gobernada, herramientas y respuesta con evidencia.'),('Operación','UI, versión, evaluación, logs, monitor y recuperación.')], 'CP8: presentar en tres minutos una pregunta de negocio y recorrer desde App hasta métrica. Explicar un límite real y qué falta para producción. No presentar el test docente como evaluación del alumno ni afirmar que todas las funcionalidades soportan toda escala.', 'S08-FINAL S08-CONTINUITY')
add('La entrega se evalúa por evidencia, no por capturas bonitas', ['Entrega notebook, configuración, respuestas y ficha de operación.','Aceptación: otra persona reproduce la consulta y localiza versión, monitor y rollback.'], 'Usar rúbrica de CONSIGNA.md. Revisar accesos de lectura del evaluador sin publicar datos crudos. Capturas complementan IDs y archivos; no sustituyen código. Un requisito no ejecutado se declara pendiente aunque el resto del paquete esté completo.', 'S08-FINAL','task')
add('Los equivalentes cloud cumplen funciones comparables', [('GCP','Vertex AI Endpoints'),('Azure','Azure ML Online Endpoints'),('AWS','SageMaker Endpoints')], 'Cápsula conceptual, no práctica de tres nubes. Comparar función de servicio de predicción; SDK, identidad, redes, autoscaling y tarifas no son idénticos. El arquitecto compara disponibilidad, integración, latencia y costo total antes de elegir.', 'S08-CLOUD','flow','gcp azure aws')
add('El examen evalúa decisiones en seis dominios', [('Diseño y datos','Traducir necesidad, preparar contexto y elegir componentes.'),('Desarrollo y despliegue','Construir agente, interfaz y proceso de entrega.'),('Gobierno y evaluación','Controlar acceso y medir calidad/operación.')], 'Abrir CERTIFICACION.md para nombres oficiales y mapa a sesiones. Guía oficial consultada: marzo 2026; volver a comprobar antes de inscribirse. El curso prepara competencias, no garantiza aprobar. Evitar dumps: practicar con preguntas originales y justificar por qué los distractores fallan.', 'S08-CERT','flow','exam')
add('Un endpoint disponible puede incumplir el contrato', [('Caso','READY y HTTP 200, pero el agente inventa cifras sin consultar datos.'),('Decisión','Detener promoción, revisar traza y repetir el harness S06.')], 'Pregunta original de repaso. Dejar que respondan antes de mostrar decisión. Conectar operación con evaluación: no sirve elevar timeout ni cambiar el color de la App para corregir un error de grounding. Pide identificar la evidencia que demostraría la corrección.', 'S08-CERT S08-CONTINUITY')
add('Mover champion no prueba que el servicio cambió', [('Pregunta','El alias apunta a v2 y el endpoint sirve v1: ¿qué inspeccionas?'),('Respuesta','Versión configurada y entidad que atendió la llamada; después aplicas y pruebas el cambio.')], 'Caso original. Diferenciar plano de registro y plano de serving. Si el alumno contesta “reiniciar el notebook”, pedir que ubique dónde se ejecuta la inferencia. La solución requiere verificar configuración efectiva y trazabilidad, no confiar en un nombre.', 'S08-CERT S08-ROLLOUT')
add('El permiso de la App no reemplaza el del usuario', [('Pregunta','Todos acceden al mismo backend con identidad compartida: ¿hay filtrado personal automático?'),('Respuesta','No. Diseña autorización por usuario o delimita un corpus común permitido.')], 'Caso original de identidad. Contrastar autenticación corporativa con autorización a documentos. No aceptar como respuesta guardar tokens personales en el browser. Pedir evidencia de una prueba permitida y otra denegada si se afirma aislamiento por usuario.', 'S08-CERT S08-APPS')
add('Una métrica de drift pide investigar antes de actuar', [('Pregunta','La longitud de preguntas sube y aún no hay etiquetas nuevas: ¿bajó la calidad?'),('Respuesta','No puede concluirse. Revisar muestras y obtener evidencia de calidad.')], 'Caso original. Pedir causa alternativa: cambio de público, temporada, interfaz o parser. No entrenar sobre respuestas no revisadas sólo porque hay drift. Conectar monitor → selección de casos → revisión humana → evaluación → cambio versionado.', 'S08-CERT S08-MONITOR')
add('Tu plan de estudio parte de errores que puedes explicar', [('Practica','Resuelve los casos originales de CERTIFICACION.md sin ver respuestas.'),('Refuerza','Vuelve a la sesión del dominio fallado y repite su laboratorio.')], 'Cerrar con un plan personal: registrar dominio, decisión errada, evidencia corregida y nueva fecha de práctica. Consultar la guía vigente antes del examen para condiciones actualizadas. Ocho clases no sustituyen práctica sostenida en el entorno.', 'S08-CERT',refs='exam')
add('Cerramos con una demostración y un límite explícito', ['Muestra una consulta, su versión, su evaluación y su señal operativa.','El siguiente paso es operar con responsables, presupuesto y criterios de negocio.'], 'Ronda de cierre: cada participante explica su recorrido y un pendiente. La aprobación del material docente sólo indica que fue preparado y revisado; el aprendizaje del alumno se demuestra con su entrega. Dejar ruta de recuperación para quien no pudo terminar por permisos o tiempos cloud.', 'S08-FINAL','hero')
for slide in slides:
 if slide['title'] in ['Un endpoint disponible puede incumplir el contrato','Mover champion no prueba que el servicio cambió','El permiso de la App no reemplaza el del usuario','Una métrica de drift pide investigar antes de actuar']:
  slide['kind']='quiz'
  slide['body']=[[slide['body'][0][1],slide['body'][1][1]]]

glossary=R/'slides/glossary.json'
if glossary.exists(): slides.append(json.loads(glossary.read_text()))

(R/'slides/content.json').write_text(json.dumps(slides,ensure_ascii=False,indent=2))
(R/'ghost-deck.md').write_text('# S08 · Lectura de títulos\n\n'+'\n'.join(f'{i+1}. {s["title"]}' for i,s in enumerate(slides))+'\n\nArco editorial: dependencia del notebook → servicio versionado → interfaz autenticada → evidencia operativa → recuperación → portafolio y certificación. Revisión del autor: cada bloque añade una decisión y culmina en una práctica; revisión independiente pendiente.\n')
(R/'sources.json').write_text(json.dumps([{'id':k,'title':k,'url':v,'checked_on':'2026-09-26','type':'official_documentation'} for k,v in REF.items()],ensure_ascii=False,indent=2))
print(len(slides),'slides content generated')
