
const slides=[...document.querySelectorAll('.slide')],byId=id=>document.getElementById(id);let i=0;
function read(k,d){try{return localStorage.getItem(k)||d}catch{return d}}function write(k,v){try{localStorage.setItem(k,v)}catch{}}
let scale=Number(read('deckEscalaS06UI','1'));if(!Number.isFinite(scale))scale=1;
function show(n){i=Math.max(0,Math.min(slides.length-1,n));slides.forEach((s,j)=>{s.classList.toggle('on',j===i);s.setAttribute('aria-hidden',String(j!==i))});byId('num').textContent=`${i+1} / ${slides.length}`;byId('bar').style.width=((i+1)/slides.length*100)+'%';history.replaceState(null,'','#'+(i+1));byId('notesTitle').textContent=slides[i].querySelector('h1,h2').textContent;byId('notesText').textContent=slides[i].querySelector('.speaker-note').textContent}
function applyScale(){scale=Math.max(.92,Math.min(1.08,scale));document.documentElement.style.setProperty('--baseFont',scale);write('deckEscalaS06UI',String(scale));byId('bMenos').disabled=scale<=.92;byId('bMas').disabled=scale>=1.08}function zoom(delta){scale=Math.round((scale+delta)*100)/100;applyScale()}
function syncTheme(){let fire=document.body.classList.contains('tema-fuego');byId('bTema').setAttribute('aria-pressed',String(fire));byId('bTema').textContent=fire?'Tema: fuego':'Tema: índigo';write('deckTemaS06UI',fire?'fuego':'indigo')}
function theme(){document.body.classList.toggle('tema-fuego');syncTheme()}
function panel(name,open){const ref=name==='refs';byId(ref?'refsPanel':'notesPanel').hidden=!open;byId(ref?'bMarcas':'bNotes').setAttribute('aria-expanded',String(open));if(open){byId(ref?'notesPanel':'refsPanel').hidden=true;byId(ref?'bNotes':'bMarcas').setAttribute('aria-expanded','false');byId(ref?'refsClose':'notesClose').focus()}else byId(ref?'bMarcas':'bNotes').focus()}
function answers(){let on=document.body.classList.toggle('show-answers');byId('bAnswers').setAttribute('aria-pressed',String(on))}
byId('bTema').onclick=theme;byId('bMenos').onclick=()=>zoom(-.04);byId('bMas').onclick=()=>zoom(.04);byId('bMarcas').onclick=()=>panel('refs',byId('refsPanel').hidden);byId('refsClose').onclick=()=>panel('refs',false);byId('bNotes').onclick=()=>panel('notes',byId('notesPanel').hidden);byId('notesClose').onclick=()=>panel('notes',false);byId('bAnswers').onclick=answers;byId('bPrev').onclick=()=>show(i-1);byId('bNext').onclick=()=>show(i+1);
addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(e.target.closest('input,textarea,select'))return;if(k==='escape'){panel('refs',false);panel('notes',false);return}if(!byId('refsPanel').hidden||!byId('notesPanel').hidden)return;if(e.target.closest('button,a')&&(k===' '||k==='enter'))return;if(['arrowright','pagedown',' '].includes(k)){e.preventDefault();show(i+1)}else if(['arrowleft','pageup'].includes(k)){e.preventDefault();show(i-1)}else if(k==='home'){e.preventDefault();show(0)}else if(k==='end'){e.preventDefault();show(slides.length-1)}else if(k==='t')theme();else if(k==='m')panel('refs',true);else if(k==='n')panel('notes',true);else if(k==='a')answers();else if(k==='+'||k==='=')zoom(.04);else if(k==='-')zoom(-.04);else if(k==='0'){scale=1;applyScale()}else if(k==='f'){if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen()}});
addEventListener('click',e=>{if(!e.target.closest('button,a,#ctl,.panel')&&byId('refsPanel').hidden&&byId('notesPanel').hidden)show(i+1)});
window.deckAudit=()=>{let restore=i,issues=[];slides.forEach((slide,index)=>{show(index);const f=slide.querySelector('.foot').getBoundingClientRect(),c=byId('ctl').getBoundingClientRect();slide.querySelectorAll('.stage,h1,h2,.body,.legend,.ey,td,.column,.node,.step,.question,.formula,.code,.example,.task,.accept').forEach(el=>{const r=el.getBoundingClientRect();if(!r.width||!r.height)return;if(r.left<12||r.right>innerWidth-12||r.top<c.bottom+8||r.bottom>f.top-14)issues.push({slide:index+1,element:el.className||el.tagName,bounds:[r.left,r.top,r.right,r.bottom],safeTop:c.bottom+8,safeBottom:f.top-14});if(el.scrollWidth>el.clientWidth+2||el.scrollHeight>el.clientHeight+2)issues.push({slide:index+1,element:el.className||el.tagName,overflow:true})})});const ui=[...document.querySelectorAll('#ctl button,#num')].map(e=>({id:e.id,r:e.getBoundingClientRect()}));for(let a=0;a<ui.length;a++){const x=ui[a];if(x.r.left<0||x.r.right>innerWidth||x.r.top<0||x.r.bottom>innerHeight)issues.push({control:x.id,outside:true});for(let b=a+1;b<ui.length;b++){let y=ui[b];if(Math.min(x.r.right,y.r.right)>Math.max(x.r.left,y.r.left)+1&&Math.min(x.r.bottom,y.r.bottom)>Math.max(x.r.top,y.r.top)+1)issues.push({controls:[x.id,y.id],overlap:true})}}show(restore);return{pass:!issues.length,slides:slides.length,viewport:[innerWidth,innerHeight],scale,theme:document.body.classList.contains('tema-fuego')?'fuego':'indigo',issues}};
window.s06={show,get index(){return i},setScale:v=>{scale=v;applyScale()},theme};
if(read('deckTemaS06UI','indigo')==='fuego')document.body.classList.add('tema-fuego');syncTheme();applyScale();show((parseInt(location.hash.slice(1))||1)-1);
