from pathlib import Path
import json
R=Path(__file__).resolve().parent
videos=[('01-ingesta-publicacion','De la fuente a los datos publicados',[
('El objetivo: conservar evidencia','SK00 · SK01', ['Fuentes SBS','Preparación trazable','Publicación controlada'], 'SBS Radar ayuda a localizar, comparar y conversar sobre documentos normativos. En este primer video seguimos la preparación: desde los PDF oficiales hasta los datos que podrá consumir el agente. Trabajamos con dos familias: seguridad de la información y ciberseguridad, y conducta de mercado. La pregunta que guía todo el flujo es sencilla: ¿podemos reconstruir de qué documento salió cada afirmación? Por eso, antes de usar un modelo, definimos el alcance y los contratos de los datos.', 'Objetivo docente: seguir la evidencia de extremo a extremo.'),
('Capturar y preservar el original','SK02 · SK08 · SK11', ['URL permitida → PDF','SHA256 → identidad','Original + procedencia'], 'La ingesta comienza con direcciones explícitas de fuentes oficiales de la SBS. Se comprueba que el destino esté permitido, se descarga el PDF y se valida su formato. Después calculamos una huella SHA doscientos cincuenta y seis. Esta huella permite identificar contenidos idénticos y evitar duplicados. Conservamos el original, la dirección de origen y el momento de captura. Atención: la huella identifica los bytes del archivo. No confirma la vigencia jurídica de una norma.', 'El hash identifica contenido; no confirma vigencia.'),
('Del PDF a pasajes verificables','SK02 · SK03', ['Página + posición','Disposición A ↔ B','Texto ≠ interpretación'], 'Extraemos el texto conservando página y posición dentro del documento. Así podemos volver desde un fragmento hasta su fuente. Luego identificamos disposiciones correspondientes en dos copias de la misma norma y alineamos el antes y el después. Separamos tres cosas: diferencia textual, interpretación del cambio e implicancia propuesta. Un salto de línea distinto no demuestra una nueva obligación. Las tablas, anexos y errores de extracción necesitan controles, y la cobertura parcial debe permanecer visible.', 'Cada comparación debe poder volver a sus dos originales.'),
('Qué contiene este piloto','SK02 · SK03 · SK09', ['6 copias · 4 resoluciones','2 familias normativas','2 pares visibles'], 'El inventario verificado contiene seis copias documentales de cuatro resoluciones. Hay dos copias de la resolución quinientos cuatro de dos mil veintiuno y dos de la tres mil doscientos setenta y cuatro de dos mil diecisiete. Además, hay una copia de la dos mil doscientos ochenta y seis de dos mil veinticuatro y otra de la dos mil doscientos veinte de dos mil veinticinco. Los dos pares visibles usan cuatro de esos seis documentos. Una opción del selector representa un par: contiene dos copias, no una sola versión.', 'Las etiquetas v4, v5, v7 y v8 no certifican vigencia.'),
('Preparar dos formas de consultar','SK04 · SK05 · SK06', ['Pasajes + embeddings','Índice local para RAG','8 tablas para Genie'], 'A partir de los pasajes preparamos un índice local para recuperación aumentada, o RAG. Los embeddings representan el significado mediante vectores, y los metadatos conservan familia, versión y fuente. En paralelo, curamos ocho tablas para consultas estructuradas: documentos, versiones, disposiciones, pares, cambios, evidencias, revisiones y procesos. Los procesos bancarios son ficticios. Genie permite contar y relacionar estas filas; RAG permite recuperar evidencia textual. Son capacidades complementarias. Este piloto utiliza un índice local: no debemos presentarlo como un servicio Vector Search desplegado.', 'RAG recupera evidencia; Genie consulta datos estructurados.'),
('Publicar no equivale a actualizar la App','SK06 · SK11 · SK12', ['publication_writer → Delta UC','cloud_writer → Volumes + control','Promoción a App: pendiente'], 'Hay dos publicadores diferentes. El publicador de Genie escribe las tablas en Delta, dentro de Unity Catalog. El publicador de artefactos escribe en Volumes y mantiene un control en Delta. Después se verifican las escrituras mediante lectura de retorno. La aplicación consume un paquete de datos verificado. Publicar artefactos nuevos no actualiza automáticamente ese paquete. En el estado documentado, el trabajo diario está pausado y la promoción automática a la aplicación sigue pendiente. Cerramos el recorrido con evidencia publicada y límites explícitos, sin confundir un piloto probado con operación continua completa.', 'Job diario pausado · promoción automática pendiente.')]),
('02-consulta-aplicacion','De la pregunta a una respuesta con evidencia',[
('Elegir el contexto de trabajo','SK10 · SK07 · SK08', ['Familia normativa','Par de copias A / B','Disposición seleccionada'], 'En este segundo video seguimos una consulta de principio a fin. La aplicación tiene tres espacios: Novedades, Comparación, y Chat y revisión. El usuario selecciona la familia normativa, el par de copias y la disposición. Por ejemplo, el artículo veinte punto tres de la resolución quinientos cuatro de dos mil veintiuno. Ese contexto acompaña la pregunta: ¿qué cambió, cómo estaba antes y cómo está ahora? Si cambiamos de familia, también deben cambiar las referencias incompatibles. Así evitamos mezclar evidencias de normas distintas.', 'Una pregunta necesita alcance documental explícito.'),
('Validar y decidir la ruta','SK07 · SK08 · SK11', ['Identidad y permisos','Alcance y límites','RAG / Genie'], 'La sesión identifica al usuario y el servidor aplica controles de acceso, alcance y consumo. Ni un texto del PDF ni un campo enviado por el navegador pueden otorgar permisos. Después se decide qué herramienta corresponde. Una pregunta como cuántas versiones tiene este par necesita datos estructurados. Una pregunta sobre qué dice un artículo necesita evidencia textual. Una solicitud de implicancias también puede necesitar generación. El enrutamiento conserva el contexto y debe declarar las limitaciones cuando la consulta sale del corpus disponible.', 'Los permisos se resuelven en el servidor.'),
('Encontrar evidencia con búsqueda híbrida','SK04 · SK05 · SK08', ['BM25 + vectores','RRF → candidatos','Reranker → EvidencePack'], 'La recuperación combina dos búsquedas dentro del alcance permitido. La búsqueda léxica, BM veinticinco, encuentra términos exactos. La búsqueda vectorial aproxima el significado. RRF fusiona las posiciones de ambas listas; no suma directamente puntuaciones que tienen escalas distintas. Después, un modelo de reranking vuelve a evaluar la relevancia de los candidatos. En este piloto el reranker se ejecuta localmente con ONNX. Finalmente reunimos pasajes, referencias, trazas y límites en un paquete de evidencia. Recuperar resultados relevantes no demuestra que hayamos cubierto toda la norma.', 'Filtrar → buscar → fusionar → reordenar → citar.'),
('Consultar tablas con Genie','SK06 · SK07', ['Pregunta de conteo','Genie → SQL Warehouse','Resultado con alcance'], 'Cuando preguntamos por cantidades o listados, Genie consulta las tablas publicadas mediante el SQL Warehouse. El adaptador aplica sus controles de alcance y procedencia. Hay una diferencia importante: el par seleccionado contiene dos copias, mientras que el inventario completo del piloto contiene seis. El resultado debe decir a qué conjunto se refiere. En la ruta de conteo puro, la respuesta tipada no pasa por el generador normativo. Eso no significa que Genie deje de ser un servicio de inteligencia artificial.', '2 copias en un par ≠ 6 copias en todo el corpus.'),
('Construir una respuesta verificable','SK07 · SK08 · SK09', ['Antes / después','Citas a evidencia','Implicancias propuestas'], 'La respuesta combina el contexto y la evidencia autorizada. La comparación preserva los pasajes anteriores y posteriores. Cuando pedimos implicancias, el modelo puede proponer puntos que revisar en los procesos bancarios ficticios. El servidor comprueba referencias y citas. Además, una revisión semántica independiente evalúa muestras y regresiones: no se ejecuta necesariamente como juez en cada pregunta. Podemos conversar sobre cambios pendientes de revisión. La aprobación institucional es una acción distinta y no está disponible en esta sesión. Una cita existente tampoco garantiza que la interpretación sea correcta.', 'Conversar está permitido; aprobar institucionalmente es distinto.'),
('Mostrar, seguir y evaluar','SK09 · SK10 · SK11 · SK12', ['Novedades → Comparación → Chat','Abrir originales y seguir preguntando','Trazas + pruebas + pendientes'], 'El alumno puede recorrer Novedades, abrir una comparación, consultar las fuentes y continuar en el chat. Puede preguntar: ¿qué evidencia respalda esa implicancia?, o ¿qué proceso ficticio convendría revisar? La aplicación reúne datos, recuperación y controles en una experiencia. La réplica con ayudas y Foquito es un tutor aparte: no ejecuta el backend de SBS Radar. Registramos trazas y evaluamos respuestas, fallos y límites. Las trece skills guían construcción, revisión y mantenimiento; no son trece llamadas por consulta. Todas siguen provisionales, y la aceptación completa del proyecto continúa abierta.', 'Demostrar el piloto con fuentes; declarar lo que sigue pendiente.')])]
for slug,title,scenes in videos:
 p=R/slug;(p/'assets').mkdir(exist_ok=True);(p/'compositions').mkdir(exist_ok=True)
 data=[]
 for i,(heading,skills,nodes,voice,note) in enumerate(scenes,1):
  rec=dict(id=f'scene{i:02}',title=heading,skills=skills,nodes=nodes,narration=voice,note=note);data.append(rec)
  (p/'assets'/f'scene{i:02}.txt').write_text(voice)
 (p/'script.json').write_text(json.dumps({'title':title,'scenes':data},ensure_ascii=False,indent=2))
 (p/'BRIEF.md').write_text(f'''---
workflow: general-video
flow: automation
storyboard: no
message: "{title}"
language: es
audience: alumnos Databricks AI Engineer
aspect: "16:9"
destination: clase
voice: ef_dora
provider: kokoro
---
## Intent
Explicar el agente real mediante dos videos complementarios, solicitados por el usuario. Narración Dora solicitada; construcción y render autorizados por la petición de crear los videos y la preferencia persistente de autonomía.
## Decisiones
1920x1080, narración clara sin música para facilitar la escucha técnica; duración guiada por voz real. Diagramas docentes, no grabación de una ejecución en vivo. Reutilizar teaching-guide y evidencia App246. No leer memoria global.
## Validación
Separar piloto probado de aceptación completa. Revisar guion de forma independiente, validar composición y audio; no declarar MP4 hasta render real.
''')
 (p/'design.md').write_text('''# Diseño SBS Radar docente
Concepto: seguir la evidencia, desde su origen hasta una respuesta verificable.
Paleta: fondo #f1f5f1, texto #173334, acento #19665e, panel #e0ebe3.
Montserrat para explicaciones; JetBrains Mono para etapas y referencias a skills. Fuentes locales.
Foco: título arriba y diagrama de flujo central con tres etapas grandes; nota pedagógica abajo. Encabezado y contador de capítulo en extremos.
Animación: spring-pop-entrance, asentamiento suave sin rebote; revelación de cada etapa con la narración. Sin efectos decorativos que distraigan.
''')
 (p/'STORYBOARD.md').write_text('\n\n'.join(f"## Frame {i}\nstatus: outline\nsrc: compositions/{s['id']}.html\nMotion: spring-pop-entrance (power3.out)\nBeat: {s['title']}\nNarración: {s['narration']}" for i,s in enumerate(data,1)))
print('12 escenas escritas; voz ef_dora; dos briefs.')
